### PR TITLE
unpin netcdf4

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bjlittle** [comment]
@conda-forge-admin, please rerender

**Comment by bjlittle** [comment]
@ocefpaf and @pelson We forgot to relax the pin on `netcdf4`... otherwise we end up in the odd situation of getting `iris 2.1` but `netcdf 1.3.1`, and forcing `netcdf 1.4.0` causes `conda` to remove `iris 2.1` from your environment. :cry:

**Comment by ocefpaf** [comment]
@bjlittle I'll move the previous build to the broken channel.

PS: it is OK to self-merge PRs like this one.

**Comment by bjlittle** [comment]
:+1: Awesome, thanks @ocefpaf

**Comment by valeriupredoi** [comment]
Cheers muchly from the ESMValTool trenches as well :)

Dr Valeriu Predoi.
Computational scientist
NCAS-CMS
University of Reading
Department of Meteorology
Reading RG6 6BB
United Kingdom

**Pull request merged**
