### PR TITLE
Rerender update

### PR DESCRIPTION
**Pull request by ocefpaf**
Replaces #11

@bjlittle you can see from #13 that even the "official" conda-smithy is broken. I re-rendered here with my hacked version to get the right matrix.

### CODE REVIEW

**Comment by bjlittle** [comment]
@ocefpaf Thanks very much! :smile: 

... Although, you did mention the "h" word ... is `conda-smithy` stable or experiencing a period of "flux" ?

**Comment by ocefpaf** [comment]
> stable or experiencing a period of "flux", shall we say ?

There were so many self-merged commits there lately that I gave it up and I work with my own version until things settle. Sadly I do not have a voice there so this forskish and terrible solution is all I got.

**Comment by bjlittle** [comment]
@ocefpaf I understand, thanks for helping out. Very much appreciated.

So who does have a voice there? @pelson ? Is it just a free for all? Please tell me that ain't so ....

**Comment by ocefpaf** [comment]
> @ocefpaf I understand, thanks for helping out. Very much appreciated.

No problem. It is in my interested to get latest version of `iris` in `conda-forge` ASAP :smile: 

> So who does have a voice there? @pelson ? Is it just a free for all? Please tell me that ain't so ....

All of conda-forge core.

BTW, you can get the same effect of my hacked version if you comment out all the dependencies but `python`, `numpy`, and `perl` and re-re-render. Then you need to un-comment them before committing.

**Pull request merged**
