### PR TITLE
Recipe updates for v3.6.0rc0

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bjlittle** [comment]
@conda-forge-admin, please rerender

**Comment by bjlittle** [comment]
Ping @conda-forge/core Help! :pray: 

Seems that we've hit an issue when attempting to rerender. I've never seen such an traceback before.

I attempted to rerender locally with `conda smithy` but hit the same issue.

Are you able to help/advise ?

Many thanks :+1:

**Comment by bjlittle** [comment]
@conda-forge-admin, please rerender

**Comment by bjlittle** [comment]
> hi @bjlittle try asking to rerender again, it looked like some temporary interruption of the webservices

I'll keep an eye on the `conda-forge` status... a blip in the matrix, I guess

**Comment by valeriupredoi** [comment]
a discontinuity in the forged space-time :grin: It rerendered now though :partying_face:

**Comment by trexfeathers** [comment]
>It rerendered now though 🥳

The cruel irony is that this was the one time when re-rendering didn't do anything 😆

**Review by trexfeathers — APPROVED** [review]
Nice job @bjlittle. I think the lack of re-render changes is probably because we did a previous release so recently 👍

**Comment by valeriupredoi** [comment]
ah yes - rerendering is pretty muted for a new version - even if rc, still a good idea to ask for it, I always ask for one, keep me in good spirits for when Skynet will eventually come :laughing: Good work, guys! :beer:

**Pull request merged**
