### PR TITLE
noarch iris

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
> @ocefpaf I don't know the best practice here... but in your opinion is it okay to make `iris` a `noarch` package without bumping the `version` (only bumping the `build number`).

It is fine to just bump the build number. No need for a new version b/c this is 100% related to the build and not the version.

> @jamesp Are you okay being added as an `iris` package maintainer

We cannot merge this unless @jamesp gives an OK.

**Comment by jamesp** [comment]
@ocefpaf @bjlittle yes good with me, thanks!

**Comment by ocefpaf** [comment]
Closing and reopening to toggle the CIs.

**Comment by ocefpaf** [comment]
We are seeing a similar breakage in other packages. Newer setuptools and pip are not happy with the newline in the description.

**Pull request merged**
