### PR TITLE
Iris release v1.11.0

### PR DESCRIPTION
**Pull request by bjlittle**
Update recipe to latest iris release of `v1.11.0`

### CODE REVIEW

**Comment by ocefpaf** [comment]
@bjlittle we need to rerender this feedstock with an updated conda-smithy to fix Travis-CI. Can you do that? I don't have my laptop with me, only a phone :-(

**Comment by bjlittle** [comment]
@ocefpaf Okay, I'll give it a try ...

**Comment by bjlittle** [comment]
@ocefpaf All the CI tests pass ... is there still an underlying problem here, regarding ...

> See conda-forge/conda-smithy#387

**Comment by ocefpaf** [comment]
Can you try adding the conda-forge channel to your .condarc and rerender again? Another workaround would be to comment out all the dependencies but python, rerender, and uncomment them again before committing.

**Comment by bjlittle** [comment]
@ocefpaf Has this done the trick? ...

**Comment by bjlittle** [comment]
@ocefpaf Is it best just for me to close this PR, and start afresh, ensuring that my `.condarc` has the `conda-forge` channel in it ? How should proceed? Thanks!

**Pull request closed without merging**
