### PR TITLE
Use mo_pack

### LINKED ISSUE #3: Depend on mo-pack, and remove the unpacking C library
It will reduce the build matrix, and offers performance as well. https://github.com/SciTools/conda-recipes-scitools/tree/master/mo_pack

### PR DESCRIPTION
**Pull request by ocefpaf**
@pelson do we need to change anything else?

Closes #3

### CODE REVIEW

**Comment by pelson** [comment]
So we can stop compiling stuff and make the setup.py call easier, as a result, this iris will be free of compiled code and no longer needs to be pinned to a specific version of numpy. I'd suggest doing this once we have the OSX build merged.

**Comment by ocefpaf** [comment]
This won't build until we solve https://github.com/conda-forge/mo_pack-feedstock/issues/6

**Comment by pelson** [comment]
Could you remove the skip, and rerender too? It will speed up testing.

**Comment by ocefpaf** [comment]
I was going to rebase and re-render. But I see you got that covered in #6. Closing this.

**Pull request closed without merging**
